#!/usr/bin/with-contenv bash

mkdir -p /config/{templates,coredns}

echo "Uname info: $(uname -a)"
# check for amneziawg kernel module
ip link del dev test 2>/dev/null
if ip link add dev test type amneziawg; then
    ip link del dev test
    if capsh --current | grep "Current:" | grep -q "cap_sys_module"; then
        echo "**** As the amneziawg module is already active you can remove the SYS_MODULE capability from your container run/compose. ****"
        echo "****     If your host does not automatically load the iptables module, you may still need the SYS_MODULE capability.     ****"
    fi
elif command -v amneziawg-go >/dev/null; then
    echo "**** The amneziawg kernel module is not active, using the amneziawg-go userspace implementation instead. ****"
    echo "****     Make sure the /dev/net/tun device is passed through to the container.     ****"
else
    echo "**** Neither the amneziawg kernel module nor the amneziawg-go userspace implementation is available. If you believe that your kernel should have amneziawg support already, make sure that it is activated via modprobe! ****"
    sleep infinity
fi
