# syntax=docker/dockerfile:1

FROM golang:1.25.12 AS awg-build
ARG AWG_RELEASE=v3.1.20260814
RUN git clone https://github.com/amnezia-vpn/amneziawg-go.git /awg && \
    cd /awg && git checkout ${AWG_RELEASE} && \
    go mod download && go mod verify && \
    go build -ldflags '-linkmode external -extldflags "-fno-PIC -static"' -v -o /usr/bin

FROM alpine:3.24 AS awg-tools-build
ARG AWG_TOOLS_RELEASE=v3.1.20260812
RUN apk add --no-cache git build-base linux-headers && \
    git clone https://github.com/amnezia-vpn/amneziawg-tools.git /amneziawg-tools && \
    cd /amneziawg-tools && git checkout ${AWG_TOOLS_RELEASE} && \
    cd src && make

FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.24

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thespad"

# install amneziawg (awg, awg-quick userspace tools and amneziawg-go userspace implementation)
COPY --from=awg-build /usr/bin/amneziawg-go /usr/bin/amneziawg-go
COPY --from=awg-tools-build /amneziawg-tools/src/wg /usr/bin/awg
COPY --from=awg-tools-build /amneziawg-tools/src/wg-quick/linux.bash /usr/bin/awg-quick

RUN \
  echo "**** install dependencies ****" && \
  apk add --no-cache \
    bc \
    coredns \
    grep \
    iproute2 \
    iptables \
    ip6tables \
    iputils \
    kmod \
    libcap-utils \
    libqrencode-tools \
    net-tools \
    nftables \
    openresolv && \
  chmod 755 /usr/bin/awg /usr/bin/awg-quick && \
  echo "amneziawg" >> /etc/modules && \
  rm -rf /etc/amnezia && \
  mkdir -p /etc/amnezia && \
  ln -s /config/wg_confs /etc/amnezia/amneziawg && \
  printf "Linuxserver.io version: ${VERSION}\nBuild-date: ${BUILD_DATE}" > /build_version && \
  echo "**** clean up ****" && \
  rm -rf \
    /tmp/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 51820/udp
