name: Mark stale issues and pull requests
on:
  schedule:
    - cron:  '20 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v11.0.0
        with:
          close-issue-label: closed-issue-activity
          close-pr-label: closed-pr-activity
          stale-issue-label: no-issue-activity
          stale-issue-message: This issue has been automatically marked as stale because it has not had recent activity. This might be due to missing feedback from OP. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-pr-label: no-pr-activity
          stale-pr-message: This pull request has been automatically marked as stale because it has not had recent activity. This might be due to missing feedback from OP. It will be closed if no further activity occurs. Thank you for your contributions.
          days-before-stale: 30
          days-before-close: 60
          exempt-issue-labels: awaiting-approval,work-in-progress
          exempt-pr-labels: awaiting-approval,work-in-progress
          operations-per-run: 400
